.shared_windows_runners:
    tags:
    - shared-windows
    - windows
    - windows-1809

stages:
    - build

release:
    extends:
        - .shared_windows_runners
    stage: build
    only:
        - tags
    artifacts:
        name: "${CI_PROJECT_NAME}-${CI_COMMIT_TAG}"
        paths:
          - ./*.zip
    script:
        - ./build --configuration Release --buildnumber $CI_PIPELINE_IID
debug:
    extends:
        - .shared_windows_runners
    stage: build
    script:
        - ./build